basePath: /api/v1
definitions:
  api_response_model.CheckCredentialResponse:
    properties:
      email:
        type: string
      is_email_verified:
        type: boolean
      is_phone_verified:
        type: boolean
      is_pin_registered:
        type: boolean
      is_registered:
        type: boolean
      is_user_exist:
        type: boolean
      phone_number:
        type: string
    type: object
  api_response_model.JwtResponse:
    properties:
      code:
        type: integer
      expire:
        type: string
      token:
        type: string
    type: object
  api_response_model.SuccessAPIResponse:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  database_model.AppConfigResponse:
    properties:
      customer_friend_phone_number:
        type: string
      maintenance:
        type: string
      minimum_version:
        type: string
      operating_time_weekday:
        type: string
      operating_time_weekend:
        type: string
    type: object
  database_model.IndonesiaArea:
    properties:
      code:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    required:
    - code
    - name
    type: object
  database_model.University:
    properties:
      acronym:
        type: string
      category:
        description: State owned (1) or private (2)
        type: integer
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      indonesiaArea:
        $ref: '#/definitions/database_model.IndonesiaArea'
      indonesiaAreaID:
        type: integer
      name:
        type: string
      nameEn:
        type: string
      status:
        description: Active (1) or Not Active (2)
        type: integer
      updatedAt:
        type: string
      website:
        type: string
      yearFounded:
        type: integer
    required:
    - name
    type: object
  database_model.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        $ref: '#/definitions/sql.NullString'
      email_verification_status:
        type: integer
      id:
        type: integer
      name:
        type: string
      phone_number:
        $ref: '#/definitions/sql.NullString'
      phone_verification_status:
        type: integer
      status:
        type: integer
      university:
        $ref: '#/definitions/database_model.University'
      universityID:
        type: integer
      updatedAt:
        type: string
      userDetail:
        $ref: '#/definitions/database_model.UserDetail'
      userDetailID:
        type: integer
    type: object
  database_model.UserDetail:
    properties:
      address_line_1:
        type: string
      address_line_2:
        type: string
      city:
        type: string
      country:
        type: string
      createdAt:
        type: string
      date_of_birth:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      document_number:
        type: string
      document_type:
        type: string
      expiry_date:
        type: string
      gender:
        type: string
      id:
        type: integer
      identity_and_selfie_image_url:
        type: string
      identity_image_url:
        type: string
      indonesiaArea:
        $ref: '#/definitions/database_model.IndonesiaArea'
      indonesiaAreaID:
        type: integer
      issue_date:
        type: string
      selfie_image_url:
        type: string
      state:
        type: string
      updatedAt:
        type: string
      zip_code:
        type: integer
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  sql.NullString:
    properties:
      string:
        type: string
      valid:
        description: Valid is true if String is not NULL
        type: boolean
    type: object
host: localhost:8083
info:
  contact:
    email: mnurilmanbaehaqi@gmail.com
    name: M Nurilman Baehaqi
    url: https://twitter.com/MOXSPOY
  description: Web service API in Go using Gin framework.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://tos.santoshk.dev
  title: Collagen Web Service
  version: "1.0"
paths:
  /app-info:
    get:
      consumes:
      - application/json
      description: This endpoint does not require token (public)
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database_model.AppConfigResponse'
      summary: Show application info metadata as the startup info while client app
        is launched
      tags:
      - App Config
  /auth/check-credential:
    post:
      consumes:
      - multipart/form-data
      description: Usually this endpoint used before validate user's identity
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      - description: Email/Phone Number
        in: formData
        name: credential
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.CheckCredentialResponse'
      summary: Check whether email or phone number exist on the database_model
      tags:
      - Auth
  /auth/refresh-token:
    post:
      description: Use this endpoint to refresh token
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.JwtResponse'
      security:
      - ApiKeyAuth: []
      summary: Refresh token
      tags:
      - Auth
  /auth/sign-up:
    post:
      consumes:
      - multipart/form-data
      description: This endpoint used to register user to the platform
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      - in: formData
        name: app_build_version
        type: integer
      - in: formData
        name: app_name_version
        type: string
      - in: formData
        name: credential
        type: string
      - in: formData
        name: device_identifier
        type: string
      - in: formData
        name: device_model
        type: string
      - in: formData
        name: email
        type: string
      - in: formData
        name: name
        type: string
      - in: formData
        name: os_version
        type: string
      - in: formData
        name: phone_number
        type: string
      - in: formData
        name: platform
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.SuccessAPIResponse'
      summary: Sign up endpoint
      tags:
      - Auth
  /auth/validate-identity:
    post:
      consumes:
      - multipart/form-data
      description: This endpoint used to check user in the platform (for login)
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      - in: formData
        name: app_build_version
        type: integer
      - in: formData
        name: app_name_version
        type: string
      - in: formData
        name: credential
        type: string
      - in: formData
        name: device_identifier
        type: string
      - in: formData
        name: device_model
        type: string
      - in: formData
        name: os_version
        type: string
      - in: formData
        name: platform
        type: string
      - in: formData
        name: request_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.JwtResponse'
      summary: Validate identity is like for login
      tags:
      - Auth
  /otp/check:
    post:
      consumes:
      - multipart/form-data
      description: Usually this endpoint used to authenticate user when doing some
        sensitive data changes
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      - description: OTP from SMS/Whatsapp to be checked
        in: formData
        name: otp
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.SuccessAPIResponse'
      security:
      - ApiKeyAuth: []
      summary: Check OTP
      tags:
      - OTP
  /otp/request:
    put:
      description: Usually this endpoint used to authenticate user when doing some
        sensitive data changes
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.SuccessAPIResponse'
      security:
      - ApiKeyAuth: []
      summary: Request OTP
      tags:
      - OTP
  /universities/all:
    get:
      description: This endpoint used to fetch all universities data
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.SuccessAPIResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all universities object
      tags:
      - User
  /universities/create:
    post:
      description: This endpoint used to create university when it is not available
        yet on the database
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      - in: formData
        name: acronym
        type: string
      - description: State owned (1) or private (2)
        in: formData
        name: category
        type: integer
      - in: formData
        name: createdAt
        type: string
      - in: formData
        name: id
        type: integer
      - in: formData
        name: indonesiaAreaID
        type: integer
      - in: formData
        name: name
        required: true
        type: string
      - in: formData
        name: nameEn
        type: string
      - description: Active (1) or Not Active (2)
        in: formData
        name: status
        type: integer
      - in: formData
        name: updatedAt
        type: string
      - in: formData
        name: website
        type: string
      - in: formData
        name: yearFounded
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.SuccessAPIResponse'
      security:
      - ApiKeyAuth: []
      summary: Create university object.
      tags:
      - User
  /user-detail/info:
    get:
      description: This endpoint used to fetch user's data but with more detail
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database_model.User'
      security:
      - ApiKeyAuth: []
      summary: Get user detail object
      tags:
      - User
  /user-detail/update:
    put:
      consumes:
      - multipart/form-data
      description: Usually this endpoint used to process kyc
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      - description: User image that will be saved to the database_model
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.SuccessAPIResponse'
      security:
      - ApiKeyAuth: []
      summary: Update user's selfie image
      tags:
      - User
  /user/info:
    get:
      description: This endpoint used to fetch user's data
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database_model.User'
      security:
      - ApiKeyAuth: []
      summary: Get user object
      tags:
      - User
  /user/update-email:
    put:
      consumes:
      - multipart/form-data
      description: Usually this endpoint used because user fill phone number first.
        Note that user need to request otp first
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      - description: Email that will be saved to the database_model
        in: formData
        name: new_email
        required: true
        type: string
      - description: OTP for authentication (if pin already exist)
        in: formData
        name: otp
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.SuccessAPIResponse'
      security:
      - ApiKeyAuth: []
      summary: Update user's email
      tags:
      - User
  /user/update-phone-number:
    put:
      consumes:
      - multipart/form-data
      description: Usually this endpoint used as part of onboarding. Note that it
        should contain country code like +6285911110000. Note that user need to request
        otp first.
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      - description: Phone number that will be saved to the database_model
        in: formData
        name: phone_number
        required: true
        type: string
      - description: OTP for authentication (if pin already exist)
        in: formData
        name: otp
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.SuccessAPIResponse'
      security:
      - ApiKeyAuth: []
      summary: Update user's phone number
      tags:
      - User
  /user/update-pin:
    put:
      consumes:
      - multipart/form-data
      description: Usually this endpoint used as part of onboarding.
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      - description: 6 digits that will be saved to the database_model
        in: formData
        name: pin
        required: true
        type: string
      - description: OTP for authentication (if pin already exist)
        in: formData
        name: otp
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.SuccessAPIResponse'
      security:
      - ApiKeyAuth: []
      summary: Update user's pin
      tags:
      - User
  /user/update-user-name:
    put:
      consumes:
      - multipart/form-data
      description: Usually this endpoint used as part of onboarding.
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      - description: Name that will be saved to the database_model
        in: formData
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.SuccessAPIResponse'
      security:
      - ApiKeyAuth: []
      summary: Update user's name
      tags:
      - User
  /user/verify-phone-number:
    put:
      consumes:
      - multipart/form-data
      description: Usually this endpoint used as part of onboarding. Note that user
        need to request otp first.
      parameters:
      - description: Api Key
        in: header
        name: api_key
        required: true
        type: string
      - description: Phone number that will be verified
        in: formData
        name: phone_number
        required: true
        type: string
      - description: OTP for authentication (if pin already exist)
        in: formData
        name: otp
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api_response_model.SuccessAPIResponse'
      security:
      - ApiKeyAuth: []
      summary: Verify user's phone number
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
