# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        touch .env
        echo API_KEY=${{ secrets.API_KEY }} >> .env
        echo JWT_KEY=${{ secrets.JWT_KEY }} >> .env
        go build -v ./...

    - name: Test
      run: |
        touch .env
        echo API_KEY=${{ secrets.API_KEY }} >> .env
        echo JWT_KEY=${{ secrets.JWT_KEY }} >> .env
        go test -v ./...

